# Generated by Django 4.2.5 on 2023-09-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_telephonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephonecode',
            name='code_type',
            field=models.CharField(default='change_telephone_code', max_length=20, verbose_name='验证码类型'),
        ),
    ]
