# Generated by Django 4.2.4 on 2023-09-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8, verbose_name='标题')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('viewcount', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
            ],
        ),
    ]
